version: '3.7'
services:
  broker:
    image: rabbitmq:3-management
    hostname: broker-mq
    container_name: broker-worker
    restart: unless-stopped
    env_file:
    - ./environment/broker.env
    ports:
      - 1200:5672
      - 2000:15672
    depends_on:
    - producer
    - consumer

  db: 
    container_name: mysql-database
    image: mysql:5.7.22
    restart: unless-stopped
    env_file:
    - ./environment/mysql.env
    volumes:
    - database:/var/lib/mysql
    ports:
    - 1100:3306

  producer:
    container_name: producer-worker
    restart: unless-stopped
    build: 
      dockerfile: Dockerfile
      context: ./producer
    env_file: 
    - ./environment/worker.env
    ports:
    - 2100:5000
    depends_on:
    - db

  consumer:
    container_name: producer-worker
    restart: unless-stopped
    build: 
      dockerfile: Dockerfile
      context: ./consumer
    env_file:
    - ./environment/worker.env
    depends_on:
    - db

volumes:
  database:
    name: mysql-data

